name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: arc-runner-set

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - run: apt update && apt install -y --no-install-recommends wget

      - run: |
          mkdir -p test_artifacts
          echo $(date) >> test_artifacts/test.txt
          wget -O test_artifacts/test.mp4 https://repo.library.stonybrook.edu/xmlui/bitstream/handle/11401/9656/rickroll.mp4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          name: test.zip
          path: ./test_artifacts
          server-root: /2BT-ARTIFACTS
          server: ${{ secrets.server }}
          user: ${{ secrets.username }}
          password: ${{ secrets.password }}
